
export const COLLECTIONS = {
  users: 'usuarios',
  stores: 'ferreterias',
  categories: 'categorias',
  subcategories: 'subcategorias',
  families: 'familias',
  familyDefinitions: 'definicionesAtributoFamilia',
  masterProducts: 'productosMaestro',
  masterAttributes: 'atributosProductoMaestro',
  storeProducts: 'productosFerreteria',
  priceHistory: 'historialPrecios',
  storeAgreements: 'contratosFerreteria',
  projects: 'proyectos',
  productRequests: 'solicitudesCreacionProducto',
  contactRequests: 'solicitudesContacto',
  consentRecords: 'registrosConsentimiento',
  marketingSuppressions: 'supresionesMarketing',
  priceReports: 'reclamosPrecios',
  privacyRequests: 'solicitudesDerechos',
  deletionReceipts: 'comprobantesEliminacion',
  adminAuditLogs: 'bitacoraAdministrativa',
  securityIncidents: 'registroIncidentesSeguridad',
  intellectualPropertyReports: 'denunciasPropiedadIntelectual',
  governanceEvidence: 'evidenciasGobiernoDatos',
  publicCache: 'cachePublico'
} as const;
