import { invalidateStaticCatalog } from '../lib/product-sheet-cache.js';
import { onDocumentWritten } from 'firebase-functions/v2/firestore';
import { markPublicCatalogDirty } from '../lib/public-catalog-cache.js';
import { useSqlDatabase } from '../database/config.js';
const dirtyFirestore = async () => { if (!useSqlDatabase()) await markPublicCatalogDirty(); };
const invalidateCatalog = async () => { if (useSqlDatabase()) return; await Promise.all([markPublicCatalogDirty(), invalidateStaticCatalog()]); };
const region = 'southamerica-west1';
export const publicCacheOnRealStoreProductWrite = onDocumentWritten({ document: 'real_productosFerreteria/{documentId}', region }, dirtyFirestore);
export const publicCacheOnMasterProductWrite = onDocumentWritten({ document: 'productosMaestro/{documentId}', region }, invalidateCatalog);
export const publicCacheOnCategoryWrite = onDocumentWritten({ document: 'categorias/{documentId}', region }, invalidateCatalog);
export const publicCacheOnSubcategoryWrite = onDocumentWritten({ document: 'subcategorias/{documentId}', region }, invalidateCatalog);
export const publicCacheOnFamilyWrite = onDocumentWritten({ document: 'familias/{documentId}', region }, invalidateCatalog);
export const publicCacheOnRealStoreWrite = onDocumentWritten({ document: 'real_ferreterias/{documentId}', region }, dirtyFirestore);
export const publicCacheOnUserWrite = onDocumentWritten({ document: 'usuarios/{documentId}', region }, dirtyFirestore);
